// priority: 0

ServerEvents.tags('item', event => {
	event.add("kubejs:ender_eyes", "endrem:black_eye")
	event.add("kubejs:ender_eyes", "endrem:cold_eye")
	event.add("kubejs:ender_eyes", "endrem:corrupted_eye")
	event.add("kubejs:ender_eyes", "endrem:lost_eye")
	event.add("kubejs:ender_eyes", "endrem:nether_eye")
	event.add("kubejs:ender_eyes", "endrem:old_eye")
	event.add("kubejs:ender_eyes", "endrem:rogue_eye")
	event.add("kubejs:ender_eyes", "endrem:cursed_eye")
	event.add("kubejs:ender_eyes", "endrem:evil_eye")
	event.add("kubejs:ender_eyes", "endrem:guardian_eye")
	event.add("kubejs:ender_eyes", "endrem:magical_eye")
	event.add("kubejs:ender_eyes", "endrem:wither_eye")
	event.add("kubejs:ender_eyes", "endrem:witch_eye")
	event.add("kubejs:ender_eyes", "endrem:undead_eye")
	event.add("kubejs:ender_eyes", "endrem:exotic_eye")
	event.add("kubejs:ender_eyes", "endrem:cryptic_eye")
})