StartupEvents.registry('item', event => {
	event.create("blaze_core").glow(true).displayName("Blaze Core")
	event.create("engineers_hammer").displayName("Engineer's Hammer")
	event.create("soul_inscriber").glow(true).displayName("Soul Inscriber")
	event.create("incomplete_basic_mechanism").texture("create_sa:item/heat_engine").displayName("Incomplete Basic Mechanism")
	event.create("basic_mechanism").texture("create_sa:item/heat_engine").glow(true).displayName("Basic Mechanism")
	event.create("dead_soul_bead").texture("quark:item/soul_bead").displayName("Dead Soul Bead")
	event.create("incomplete_soul_enclosure").texture("create_sa:item/small_filling_tank").displayName("Incomplete Soul Enclosure")
	event.create("soul_enclosure").texture("create_sa:item/small_filling_tank").glow(true).displayName("Soul Enclosure")
	event.create("unenchanted_book").texture("minecraft:item/enchanted_book").displayName("Unenchanted Book")

	event.create("solid_fuel").burnTime(2400).displayName("Solid Fuel")
	event.create("plastic_bar").displayName("Plastic Bar")
	event.create("raw_silicon_dust").displayName("Raw Silicon Dust")
	event.create("silicon_wafer").displayName("Silicon Wafer")
	event.create("laser_ram_engraver").displayName("Laser RAM Engraver")
	event.create("engraved_ram_wafer").maxStackSize(1).displayName("Engraved RAM Wafer")
	event.create("ram_chip").displayName("RAM Chip")
	event.create("engraved_cpu_wafer").maxStackSize(1).displayName("Engraved CPU Wafer")
	event.create("laser_cpu_engraver").displayName("Laser CPU Engraver")
	event.create("cpu_chip").displayName("CPU Chip")
	event.create("incomplete_microcontroller").texture("kubejs:item/microcontroller").displayName("Incomplete Microcontroller")
	event.create("microcontroller").glow(true).displayName("Microcontroller")
})

